### ISSUE TITLE
Consider visually denoting drafts

### ISSUE THREAD

**Issue by apreshill** [yihui/hugo-prose#7]
I love this feature from the [paperesque](https://github.com/capnfabs/paperesque/) theme, where all drafts have clear diagonal lines on the listing page and the full article page. 

Full article: https://themes.gohugo.io/theme/paperesque/posts/magpie/

Simple CSS in the layout file:
https://github.com/capnfabs/paperesque/blob/228903d2bad09f92d4de8a2922806fafd24d3966/layouts/_default/single.html#L1-L3

Listing page: https://themes.gohugo.io/theme/paperesque/posts/

CSS again:
https://github.com/capnfabs/paperesque/blob/228903d2bad09f92d4de8a2922806fafd24d3966/layouts/_default/list.html#L7-L19

<img width="923" alt="Screen Shot 2020-11-11 at 6 14 21 AM" src="https://user-images.githubusercontent.com/12160301/98805186-30508b80-23e5-11eb-9698-329eea5bef68.png">
<img width="923" alt="Screen Shot 2020-11-11 at 6 16 03 AM" src="https://user-images.githubusercontent.com/12160301/98805319-65f57480-23e5-11eb-9f6d-90ba2e98a8c3.png">

**Comment by yihui** [comment]
Done. Demo: https://prose.yihui.org/post/2019/07/29/letter-3-on-true-and-false-friendship/

I added a watermark because otherwise we'll have to explain what the diagonal lines mean. Not sure if the watermark would interfere with reading.

Colors can be tweaked later. I just copied the one line of CSS from paperesque.

## Listing

![image](https://user-images.githubusercontent.com/163582/98870249-a92d0300-2438-11eb-92c6-132c88ac1fa8.png)

## Single page

![image](https://user-images.githubusercontent.com/163582/98870162-839ff980-2438-11eb-9989-fdd1557d86dc.png)
